compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 14d

npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
