name: Test CI

on: push

permissions:
  contents: write # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Install rust target
        run: rustup target add x86_64-apple-darwin

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build workspaces
        run: yarn build

      - name: Run Test
        run: yarn test
